version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    depends_on:
      - db
  db:
    image: mysql:8.3
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
